version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: bookstore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: bookstore_db
    ports:
      - "5432:5432"
    networks:
      - bookstore-network

  bookstore:
    build: .
    container_name: bookstore-app
    ports:
      - "6565:6565"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstore_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass123
      GRPC_SERVER_HOST: 0.0.0.0
      GRPC_SERVER_PORT: 6565
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge